<?php
/*
 * @category    Sezzle
 * @package     Sezzle_Sezzlepay
 * @copyright   Copyright (c) Sezzle (https://www.sezzle.com/)
 */
?>
<?php
use Sezzle\Sezzlepay\Block\Widget\Cart;
/** @var $block Cart */
?>
<?php if ($block->isWidgetEnabledForCartPage()) : ?>
<script type="text/x-magento-init">
    {
        "*": {
            "widgetRenderer": {
                "is_static_widget" : <?php echo $block->isStaticWidgetEnabled(); ?>,
                "merchant_uuid" : "<?php echo $block->getMerchantUUID(); ?>",
                "price" : "<?php echo $block->getGrandTotal() ?>",
                "alignment" : "<?php echo $block->getAlignment() ?>",
                "is_cart" : true
            }
        }
    }
</script>
<?php endif; ?>
