<?php
/*
 * @category    Sezzle
 * @package     Sezzle_Payment
 * @copyright   Copyright (c) Sezzle (https://www.sezzle.com/)
 */
?>
<?php if ($this->isWidgetScriptAllowedForCartPage()) : ?>
<script type="text/x-magento-init">
    {
        "*": {
            "widgetRenderer": {
                "merchant_id" : "<?php echo $this->getMerchantID() ?>"
            }
        }
    }
</script>
<?php endif; ?>
