<?php
/*
 * @category    Sezzle
 * @package     Sezzle_Sezzlepay
 * @copyright   Copyright (c) Sezzle (https://www.sezzle.com/)
 */
?>
<?php
use Sezzle\Sezzlepay\Block\Widget\Cart;
/** @var $block Cart */
?>
<?php if ($block->isWidgetEnabledForCartPage()) : ?>
<script type="text/x-magento-init">
    {
        "*": {
            "widgetRenderer": {
                "price" : "<?php echo $block->getGrandTotal() ?>",
                "alignment" : "<?php echo $block->getAlignment() ?>",
                "is_cart" : true,
                "widget_type" : "<?php echo $block->getWidgetType(); ?>",
                "widget_url" : "<?php echo $block->getWidgetUrl(); ?>"
            }
        }
    }
</script>
<script type='text/javascript'>
                    Sezzle = {}
                    Sezzle.render = function () {
                        document.sezzleConfig = {
      "configGroups": [
              {
                      "targetXPath": ".product-info-main/.price-wrapper/.price",
                      "renderToPath": "../../../..",
                      "relatedElementActions": [
                              {
                                      "relatedPath": ".",
                                      "initialAction": function(r,w){
                                              if(getComputedStyle(r).textDecoration.indexOf("line-through") > -1){
                                                      w.style.display = "none"
                                              }
                                      }
                              }
                      ]
              },
              {
                      "targetXPath": ".amount/STRONG-0/.price",
                      "renderToPath": "../../../../..",
                      "urlMatch": "cart"
              }
      ]
}
                        var script = document.createElement('script');
                        script.type = 'text/javascript';
                        script.src = '<?php echo $block->getWidgetUrl(); ?>';
                        document.head.appendChild(script);
                    };
                    Sezzle.render();
                </script>
<?php endif; ?>
