<?php
/*
 * @category    Sezzle
 * @package     Sezzle_Sezzlepay
 * @copyright   Copyright (c) Sezzle (https://www.sezzle.com/)
 */
?>
<?php

use Sezzle\Sezzlepay\Block\Widget\Installment;

/** @var $block Installment */
?>
<?php if ($block->isInstallmentWidgetEnabled()) : ?>
    <script type="text/javascript">
        require(['installmentWidgetSDK'], function () {
            new SezzleInstallmentWidget({
                'merchantLocale': 'US',
                'platform': 'magento2'
            });
        });
    </script>
<?php endif; ?>
