<?php
/*
 * @category    Sezzle
 * @package     Sezzle_Sezzlepay
 * @copyright   Copyright (c) Sezzle (https://www.sezzle.com/)
 */
?>
<?php
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Sezzle\Sezzlepay\Block\Widget\Installment;

/**  @var SecureHtmlRenderer $secureRenderer */
/**  @var Installment $block */
?>
<?php if ($block->isInstallmentWidgetEnabled()) : ?>
    <?php $script = <<<SCRIPT
        require(['installmentWidgetSDK'], function () {
            new SezzleInstallmentWidget({
            'merchantLocale': 'US',
            'platform': 'magento2'
            });
        });
    SCRIPT; ?>

    <?php echo $secureRenderer->renderTag('script', [], $script, false); ?>
<?php endif; ?>
