<?php
/*
 * @category    Sezzle
 * @package     Sezzle_Sezzlepay
 * @copyright   Copyright (c) Sezzle (https://www.sezzle.com/)
 */

// @codingStandardsIgnoreFile
?>

<?php

use Sezzle\Sezzlepay\Block\Adminhtml\Order\View\Info;
use Sezzle\Sezzlepay\Model\Ui\ConfigProvider;

/** @var Info $block */

$order = $block->getOrder();

$orderAdminDate = $block->formatDate(
    $block->getOrderAdminDate($order->getCreatedAt()),
    \IntlDateFormatter::MEDIUM,
    true
);

$orderStoreDate = $block->formatDate(
    $order->getCreatedAt(),
    \IntlDateFormatter::MEDIUM,
    true,
    $block->getTimezoneForStore($order->getStore())
);

$customerUrl = $block->getCustomerViewUrl();
$allowedAddressHtmlTags = ['b', 'br', 'em', 'i', 'li', 'ol', 'p', 'strong', 'sub', 'sup', 'ul'];
?>

<?php if ($block->isSezzleOrder()) : ?>
    <section class="admin__page-section order-view-account-information sezzle">
        <div class="admin__page-section-title">
            <span class="title"><?= $block->escapeHtml(__('Sezzle Information')) ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-information sezzle">
                <?php /* Sezzle Order Information */ ?>
                <div class="admin__page-section-item-title">
                    <span class="title">
                        <?= $block->escapeHtml(__('Order Reference # %1', $block->getOrderReferenceID())) ?>
                    </span>
                </div>
                <div class="admin__page-section-item-content">
                    <table class="admin__table-secondary order-information-table">
                        <?php if ($authorizedAmount = $block->getAuthorizedAmount()) : ?>
                            <tr>
                                <th><?= $block->escapeHtml(__('Authorized Amount')) ?></th>
                                <td><?= $block->escapeHtml($authorizedAmount); ?></td>
                            </tr>
                        <?php endif; ?>
                        <?php if ($capturedAmount = $block->getCapturedAmount()) : ?>
                            <tr>
                                <th><?= $block->escapeHtml(__('Captured Amount')) ?></th>
                                <td><?= $block->escapeHtml($capturedAmount); ?></td>
                            </tr>
                        <?php endif; ?>
                        <?php if ($refundedAmount = $block->getRefundedAmount()) : ?>
                            <tr>
                                <th><?= $block->escapeHtml(__('Refunded Amount')) ?></th>
                                <td><?= $block->escapeHtml($refundedAmount); ?></td>
                            </tr>
                        <?php endif; ?>
                        <?php if ($releasedAmount = $block->getReleasedAmount()) : ?>
                            <tr>
                                <th><?= $block->escapeHtml(__('Released Amount')) ?></th>
                                <td><?= $block->escapeHtml($releasedAmount); ?></td>
                            </tr>
                        <?php endif; ?>
                        <?php if ($authExpiry = $block->getAuthExpiry()) : ?>
                            <tr>
                                <th><?= $block->escapeHtml(__('Auth Expiry')) ?></th>
                                <td>
                                    <?php if ($block->isAuthExpired()) : ?>
                                        <style>
                                            .sezzle-auth-expiry {
                                                color: #ff0000
                                            }
                                        </style>
                                    <?php endif; ?>
                                    <span class="sezzle-auth-expiry">
                                        <strong>
                                            <?= $block->escapeHtml($authExpiry); ?> <br>
                                        </strong>
                                    </span>
                                </td>
                            </tr>
                        <?php endif; ?>
                    </table>
                </div>
            </div>

            <?php if ($block->isTokenizedDataAvailable()) : ?>
                <div class="admin__page-section-item order-account-information sezzle">
                    <?php /* Sezzle Account Information */ ?>
                    <div class="admin__page-section-item-title">
                        <span class="title"><?= $block->escapeHtml(__('Customer Information')) ?></span>
                    </div>
                    <div class="admin__page-section-item-content">
                        <table class="admin__table-secondary order-account-information-table">
                            <?php if ($customerUUID = $block->getCustomerUUID()) : ?>
                                <tr>
                                    <th><?= $block->escapeHtml(__('Customer UUID')) ?></th>
                                    <td><?= $block->escapeHtml($customerUUID) ?></td>
                                </tr>
                            <?php endif; ?>
                            <?php if ($customerUUIDExpiration = $block->getCustomerUUIDExpiration()) : ?>
                                <tr>
                                    <th><?= $block->escapeHtml(__('Customer UUID Expiration')) ?></th>
                                    <td><?= $block->escapeHtml($customerUUIDExpiration) ?></td>
                                </tr>
                            <?php endif; ?>
                        </table>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </section>
<?php endif; ?>
