<?php
/*
 * @category    Sezzle
 * @package     Sezzle_Sezzlepay
 * @copyright   Copyright (c) Sezzle (https://www.sezzle.com/)
 */

 // @codingStandardsIgnoreFile
?>

<?php

use Sezzle\Sezzlepay\Block\Adminhtml\Order\View\Info;
use Sezzle\Sezzlepay\Model\Sezzle;
use Sezzle\Sezzlepay\Model\System\Config\Container\SezzleIdentity;

/** @var Info $block */

$order = $block->getOrder();

$orderAdminDate = $block->formatDate(
    $block->getOrderAdminDate($order->getCreatedAt()),
    \IntlDateFormatter::MEDIUM,
    true
);

$orderStoreDate = $block->formatDate(
    $order->getCreatedAt(),
    \IntlDateFormatter::MEDIUM,
    true,
    $block->getTimezoneForStore($order->getStore())
);

$customerUrl = $block->getCustomerViewUrl();
$allowedAddressHtmlTags = ['b', 'br', 'em', 'i', 'li', 'ol', 'p', 'strong', 'sub', 'sup', 'ul'];
?>

<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Order & Account Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <?php /* Order Information */ ?>
            <?php $confirmationEmailStatusMessage = $order->getEmailSent() ? __('The order confirmation email was sent') : __('The order confirmation email is not sent'); ?>
            <div class="admin__page-section-item-title">
                <span class="title">
                    <?php if ($block->getNoUseOrderLink()): ?>
                        <?= $block->escapeHtml(__('Order # %1', $order->getRealOrderId())) ?> (<span><?= $block->escapeHtml($confirmationEmailStatusMessage) ?></span>)
                    <?php else: ?>
                        <a href="<?= $block->escapeHtml($block->getViewUrl($order->getId())) ?>"><?= $block->escapeHtml(__('Order # %1', $order->getRealOrderId())) ?></a>
                        <span>(<?= $block->escapeHtml($confirmationEmailStatusMessage) ?>)</span>
                    <?php endif; ?>
                </span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                <tr>
                    <th><?= $block->escapeHtml(__('Order Date')) ?></th>
                    <td><?= $block->escapeHtml($orderAdminDate) ?></td>
                </tr>
                <?php if ($orderAdminDate != $orderStoreDate):?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Order Date (%1)', $block->getTimezoneForStore($order->getStore()))) ?></th>
                        <td><?= $block->escapeHtml($orderStoreDate) ?></td>
                    </tr>
                <?php endif;?>
                <tr>
                    <th><?= $block->escapeHtml(__('Order Status')) ?></th>
                    <td><span id="order_status"><?= $block->escapeHtml($order->getStatusLabel()) ?></span></td>
                </tr>
                <?= $block->getChildHtml() ?>
                <?php if ($block->isSingleStoreMode() == false):?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Purchased From')) ?></th>
                        <td><?= $block->escapeHtml($block->getOrderStoreName(), ['br']) ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($order->getRelationChildId()): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Link to the New Order')) ?></th>
                        <td>
                            <a href="<?= $block->escapeHtml($block->getViewUrl($order->getRelationChildId())) ?>">
                                <?= $block->escapeHtml($order->getRelationChildRealId()) ?>
                            </a>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php if ($order->getRelationParentId()): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Link to the Previous Order')) ?></th>
                        <td>
                            <a href="<?= $block->escapeHtml($block->getViewUrl($order->getRelationParentId())) ?>">
                                <?= $block->escapeHtml($order->getRelationParentRealId()) ?>
                            </a>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php if ($order->getRemoteIp() && $block->shouldDisplayCustomerIp()): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Placed from IP')) ?></th>
                        <td><?= $block->escapeHtml($order->getRemoteIp()); echo $order->getXForwardedFor() ? ' (' . $block->escapeHtml($order->getXForwardedFor()) . ')' : ''; ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($order->getGlobalCurrencyCode() != $order->getBaseCurrencyCode()): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('%1 / %2 rate:', $order->getGlobalCurrencyCode(), $order->getBaseCurrencyCode())) ?></th>
                        <td><?= $block->escapeHtml($order->getBaseToGlobalRate()) ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($order->getBaseCurrencyCode() != $order->getOrderCurrencyCode()): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('%1 / %2 rate:', $order->getOrderCurrencyCode(), $order->getBaseCurrencyCode())) ?></th>
                        <td><?= $block->escapeHtml($order->getBaseToOrderRate()) ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($block->getSezzleOrderType() != SezzleIdentity::API_VERSION_V2
                    && $block->getSezzleCaptureExpiry()
                    && $order->getPayment()->getMethod() == Sezzle::PAYMENT_CODE) : ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Sezzle Capture Expiry')) ?></th>
                        <td>
                            <strong>
                                <?= $block->escapeHtml($block->getSezzleCaptureExpiry()); ?> <br>
                            </strong>
                            <?= $block->escapeHtml($block->getCaptureInfo()); ?>
                        </td>
                    </tr>
                <?php endif; ?>
                </table>
            </div>
        </div>

        <div class="admin__page-section-item order-account-information">
            <?php /* Account Information */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Account Information')) ?></span>
                <div class="actions">
                    <?php if ($customerUrl) : ?>
                        <a href="<?= /* @noEscape */ $customerUrl ?>" target="_blank">
                            <?= $block->escapeHtml(__('Edit Customer')) ?>
                        </a>
                    <?php endif; ?>
                </div>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tr>
                        <th><?= $block->escapeHtml(__('Customer Name')) ?></th>
                        <td>
                            <?php if ($customerUrl): ?>
                                <a href="<?= $block->escapeUrl($customerUrl) ?>" target="_blank">
                                    <span><?= $block->escapeHtml($order->getCustomerName()) ?></span>
                                </a>
                            <?php else: ?>
                                <?= $block->escapeHtml($order->getCustomerName()) ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Email')) ?></th>
                        <td><a href="mailto:<?php echo $block->escapeHtml($order->getCustomerEmail()) ?>"><?php echo $block->escapeHtml($order->getCustomerEmail()) ?></a></td>
                    </tr>
                    <?php if ($groupName = $block->getCustomerGroupName()) : ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('Customer Group')) ?></th>
                            <td><?= $block->escapeHtml($groupName) ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php foreach ($block->getCustomerAccountData() as $data):?>
                        <tr>
                            <th><?= $block->escapeHtml($data['label']) ?></th>
                            <td><?= $block->escapeHtml($data['value'], ['br']) ?></td>
                        </tr>
                    <?php endforeach;?>
                    <?= $block->getChildHtml('extra_customer_info') ?>
                </table>
            </div>
        </div>


    </div>
</section>

<?php if (($order->getPayment()->getMethod() == Sezzle::PAYMENT_CODE)
        && $block->getSezzleOrderType() == SezzleIdentity::API_VERSION_V2) : ?>
    <section class="admin__page-section order-view-account-information sezzle">
        <div class="admin__page-section-title">
            <span class="title"><?= $block->escapeHtml(__('Sezzle Information')) ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-information sezzle">
                <?php /* Sezzle Order Information */ ?>
                <div class="admin__page-section-item-title">
                    <span class="title">
                        <?= $block->escapeHtml(__('Order Reference # %1', $block->getSezzleOrderReferenceID())) ?>
                    </span>
                </div>
                <div class="admin__page-section-item-content">
                    <table class="admin__table-secondary order-information-table">
                        <?php if ($sezzleAuthAmount = $block->getSezzleAuthAmount()) : ?>
                            <tr>
                                <th><?= $block->escapeHtml(__('Auth Amount')) ?></th>
                                <td><?= $block->escapeHtml($sezzleAuthAmount); ?></td>
                            </tr>
                        <?php endif; ?>
                        <?php if ($sezzleCapturedAmount = $block->getSezzleCaptureAmount()) : ?>
                            <tr>
                                <th><?= $block->escapeHtml(__('Captured Amount')) ?></th>
                                <td><?= $block->escapeHtml($sezzleCapturedAmount); ?></td>
                            </tr>
                        <?php endif; ?>
                        <?php if ($sezzleRefundedAmount = $block->getSezzleRefundAmount()) : ?>
                            <tr>
                                <th><?= $block->escapeHtml(__('Refunded Amount')) ?></th>
                                <td><?= $block->escapeHtml($sezzleRefundedAmount); ?></td>
                            </tr>
                        <?php endif; ?>
                        <?php if ($sezzleReleasedAmount = $block->getSezzleReleaseAmount()) : ?>
                            <tr>
                                <th><?= $block->escapeHtml(__('Released Amount')) ?></th>
                                <td><?= $block->escapeHtml($sezzleReleasedAmount); ?></td>
                            </tr>
                        <?php endif; ?>
                        <?php if ($sezzleAuthExpiry = $block->getSezzleAuthExpiry()) : ?>
                            <tr>
                                <th><?= $block->escapeHtml(__('Auth Expiry')) ?></th>
                                <td>
                                    <?php if ($block->isAuthExpired()) : ?>
                                    <style>
                                        .sezzle-auth-expiry {
                                            color: #ff0000
                                        }
                                    </style>
                                    <?php endif; ?>
                                    <span class="sezzle-auth-expiry">
                                        <strong>
                                            <?= $block->escapeHtml($sezzleAuthExpiry); ?> <br>
                                        </strong>
                                    </span>
                                </td>
                            </tr>
                        <?php endif; ?>
                    </table>
                </div>
            </div>

            <?php if ($block->isTokenizedDataAvailable()) : ?>
            <div class="admin__page-section-item order-account-information sezzle">
                <?php /* Sezzle Account Information */ ?>
                <div class="admin__page-section-item-title">
                    <span class="title"><?= $block->escapeHtml(__('Customer Information')) ?></span>
                </div>
                <div class="admin__page-section-item-content">
                    <table class="admin__table-secondary order-account-information-table">
                        <?php if ($sezzleCustomerUUID = $block->getSezzleCustomerUUID()) : ?>
                            <tr>
                                <th><?= $block->escapeHtml(__('Customer UUID')) ?></th>
                                <td><?= $block->escapeHtml($sezzleCustomerUUID) ?></td>
                            </tr>
                        <?php endif; ?>
                        <?php if ($sezzleCustomerUUIDExpiration = $block->getSezleCustomerUUIDExpiration()) : ?>
                            <tr>
                                <th><?= $block->escapeHtml(__('Customer UUID Expiration')) ?></th>
                                <td><?= $block->escapeHtml($sezzleCustomerUUIDExpiration) ?></td>
                            </tr>
                        <?php endif; ?>
                    </table>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </section>
<?php endif; ?>

<section class="admin__page-section order-addresses">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Address Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-billing-address">
            <?php /* Billing Address */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Billing Address')) ?></span>
                <div class="actions"><?= /* @noEscape */ $block->getAddressEditLink($order->getBillingAddress()); ?></div>
            </div>
            <address class="admin__page-section-item-content"><?= $block->escapeHtml($block->getFormattedAddress($order->getBillingAddress()), $allowedAddressHtmlTags); ?></address>
        </div>
        <?php if (!$block->getOrder()->getIsVirtual()): ?>
            <div class="admin__page-section-item order-shipping-address">
                <?php /* Shipping Address */ ?>
                <div class="admin__page-section-item-title">
                    <span class="title"><?= $block->escapeHtml(__('Shipping Address')) ?></span>
                    <div class="actions"><?= /* @noEscape */ $block->getAddressEditLink($order->getShippingAddress()); ?></div>
                </div>
                <address class="admin__page-section-item-content"><?= $block->escapeHtml($block->getFormattedAddress($order->getShippingAddress()), $allowedAddressHtmlTags); ?></address>
            </div>
        <?php endif; ?>
    </div>
</section>
