<?php
/*
 * @category    Sezzle
 * @package     Sezzle_Sezzlepay
 * @copyright   Copyright (c) Sezzle (https://www.sezzle.com/)
 */
?>
<?php
use Sezzle\Sezzlepay\Block\Cart\ExpressCheckout;
/** @var $block ExpressCheckout */
?>
<?php if ($block->canDisplay()) : ?>
<script type="text/javascript">
    window.checkoutConfig = <?= /* @noEscape */ $block->getSerializedCheckoutConfig() ?>;
</script>
<div id="sezzle-express-checkout" data-bind="scope: 'sezzle-express-checkout'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "#sezzle-express-checkout": {
        "Magento_Ui/js/core/app": {
            "components": {
                "sezzle-express-checkout": {
                    "component": "Sezzle_Sezzlepay/js/view/cart/sezzle-express-checkout"
                }
            }
        }
    }
}
</script>
<?php endif; ?>
