<?php
/*
 * @category    Sezzle
 * @package     Sezzle_Sezzlepay
 * @copyright   Copyright (c) Sezzle (https://www.sezzle.com/)
 */
?>
<?php /** @var $block \Sezzle\Sezzlepay\Block\Order\Info */ ?>

<?php if ($block->isSezzleOrder()) : ?>
    <div class="order-date">
        <span class="text-label">Sezzle Order Reference ID:</span>
        <date><strong><?= $block->escapeHtml($block->getOrderReferenceID()) ?></strong></date>
    </div>
    <br>
<?php endif; ?>
