<?php

use Sezzle\Sezzlepay\Block\Adminhtml\System\Config\Field\WidgetQueue;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var SecureHtmlRenderer $secureRenderer */
/** @var WidgetQueue $block */
?>
<?php
$canAddToWidgetQueue = $block->canAddToWidgetQueue() ? 'true' : 'false';
$widgetQueueUrl = $block->escapeJs($block->escapeUrl($block->getWidgetQueueUrl()));
$script = <<<SCRIPT
    require([
        'jquery',
        'mage/translate',
        'Magento_Ui/js/modal/alert'
    ], function ($, \$t, alert) {
        var canAddToWidgetQueue = {$canAddToWidgetQueue},
            widgetQueueElement = $('#widget_queue');
        
        if (!widgetQueueElement.length) {
            return; // Element not found, exit early
        }
        
        if (!canAddToWidgetQueue) {
            widgetQueueElement.text(\$t("Request Submitted")).prop('disabled', true);
            return;
        }

        widgetQueueElement.on('click', function () {
            var self = $(this);
            self.text(\$t("Adding to widget queue...")).prop('disabled', true);

            $.ajax({
                url: '{$widgetQueueUrl}',
                type: 'POST',
                data: {
                    form_key: window.FORM_KEY
                },
                showLoader: true,
                success: function () {
                    console.log("Sezzle: Request successfully added to widget queue");
                    self.text(\$t("Request Submitted"));
                    alert({
                        title: \$t('Sezzle Widget Queue Request'),
                        content: \$t('Your request for help was successfully submitted.  Please allow 2 business days for a response.')
                    });
                },
                error: function () {
                    console.error("Sezzle: Request failed to get added to widget queue");
                    self.text(\$t("Request")).prop('disabled', false);
                    alert({
                        title: \$t('Sezzle Widget Queue Request'),
                        content: \$t('There was an error submitting your request. Please try again.')
                    });
                }
            });
        });
    });
SCRIPT;
?>

<?php /* @noEscape */ echo $secureRenderer->renderTag('script', [], $script, false); ?>
<?php echo $block->getButtonHtml() ?>
