<?php
/**
 * @category    Sezzle
 * @package     Sezzle_Sezzlepay
 * @copyright   Copyright (c) Sezzle (https://www.sezzle.com/)
 */

use Sezzle\Sezzlepay\Block\Adminhtml\SettlementReports\PayoutDetails\View\LineItems\Renderer\DefaultRenderer;

?>
<?php /** @var  $block DefaultRenderer */ ?>
<?php $item = $block->getLineItem() ?>
<tr>
    <?php $i = 0;
    $columns = $block->getColumns();
    $lastItemNumber = count($columns) ?>
    <?php foreach ($columns as $columnName => $columnClass) : ?>
        <?php $i++; ?>
        <td class="<?= /* @noEscape */ $columnClass ?><?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>">
            <?= $item[$columnName] ?>
        </td>
    <?php endforeach; ?>
</tr>
