<?php
/**
 * @category    Sezzle
 * @package     Sezzle_Sezzlepay
 * @copyright   Copyright (c) Sezzle (https://www.sezzle.com/)
 */

use Sezzle\Sezzlepay\Block\Adminhtml\SettlementReports\PayoutDetails\View\Tab\LineItems;

/**
 * @var LineItems $block
 */ ?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary edit-order-table">
        <thead>
        <tr class="headings">
            <?php $i = 0;
            $columns = $block->getColumns();
            $lastItemNumber = count($columns) ?>
            <?php foreach ($columns as $columnName => $columnTitle) : ?>
                <?php $i++; ?>
                <th class="col-<?= $block->escapeHtmlAttr($columnName) ?><?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>"><span><?= $block->escapeHtml($columnTitle) ?></span></th>
            <?php endforeach; ?>
        </tr>
        </thead>
        <?php $_items = $block->getColumnData();?>
        <?php foreach ($_items as $_item) : ?>
            <tbody class="<?= /* @noEscape */ $i%2 ? 'even' : 'odd' ?>">
            <?= $block->getLineItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
</div>
