<?php
/**
 * @category    Sezzle
 * @package     Sezzle_Sezzlepay
 * @copyright   Copyright (c) Sezzle (https://www.sezzle.com/)
 */

use Sezzle\Sezzlepay\Block\Adminhtml\SettlementReports\PayoutDetails\View\Tab\Summary;

/** @var $block Summary */
$data = $block->getColumnData();

?>

<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Payout Summary')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div style="width: 70%" class="admin__page-section-item order-information">
            <?php /* Order Information */ ?>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <?php foreach ($block->getColumnNames() as $columnName) : ?>
                    <tr>
                        <th><?= $block->escapeHtml(__($block->getColumnName($columnName))) ?></th>
                        <td><?= $block->escapeHtml($data[$columnName]) ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
</section>
